### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by zuphilip** [lmatthia/publisher-oa-portfolios#1]
The currency of the numbers is not mentioned. I guess that most of the numbers should be treated as USD. If you want to normalize that everything is in EUR than you may have to mention how you transform other currencies into USD (exchange rate in that year, when exactly?).

Moreover, it seems also that some publishers (e.g. Elsevier) mix different currencies in their table. E.g. the APC of Computational and Structural Biotechnology Journal (2001-0370) in the 2018 list is given in EUR where you have the same information without any indications:

https://github.com/lmatthia/publisher-oa-portfolios/blob/e258c0d62418a9a6b38ec92bca6cc0f0e844ffc1/elsevier_oa_and_hybrid.csv#L10173-L10174

Sometimes I find also `EUR` in your list, e.g. https://github.com/lmatthia/publisher-oa-portfolios/blob/e258c0d62418a9a6b38ec92bca6cc0f0e844ffc1/elsevier_oa_and_hybrid.csv#L2875

Another idea: Maybe you want to mention that these APCs are without any tax which means that in reality one has to pay much more than just the APCs from the lists here. (It is 19% on top for taxes on APCs in Germany.)

**Comment by lmatthia** [comment]
It says in the Readme file that prices are in USD, but I'll add that these are excluding taxes! I'm also working to normalize currencies I haven't yet. :)

**Comment by lmatthia** [comment]
finally fixed ;)
